services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: scriptdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  node:
    build: .
    container_name: node-app
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: scriptdb
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]



